import os
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

# Verify if the environment variables were successfully loaded

# Google Cloud Configuration
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
PROJECT_ID = os.getenv("PROJECT_ID")
LOCATION = os.getenv("LOCATION")
GOOGLE_GENAI_USE_VERTEXAI = os.getenv("GOOGLE_GENAI_USE_VERTEXAI")
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT")
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION")

# Vertex AI Search (RAG)
DATASTORE_PROJECT_ID = os.getenv("DATASTORE_PROJECT_ID")
DATASTORE_LOCATION = os.getenv("DATASTORE_LOCATION")
DATASTORE_ENGINE_ID = os.getenv("DATASTORE_ENGINE_ID")

# Toolbox URL
TOOLBOX_URL = os.getenv("TOOLBOX_URL")

# MySQL for MCP Toolbox
MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_PORT = os.getenv("MYSQL_PORT")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")

# Global Gemini model
GEMINI_MODEL = os.getenv("GEMINI_MODEL")

print(f"GOOGLE_APPLICATION_CREDENTIALS : {GOOGLE_APPLICATION_CREDENTIALS}")
print(f"PROJECT_ID : {PROJECT_ID}")
print(f"LOCATION : {LOCATION}")
print(f"GOOGLE_GENAI_USE_VERTEXAI : {GOOGLE_GENAI_USE_VERTEXAI}")
print(f"GOOGLE_CLOUD_PROJECT : {GOOGLE_CLOUD_PROJECT}")
print(f"GOOGLE_CLOUD_LOCATION : {GOOGLE_CLOUD_LOCATION}")
print(f"DATASTORE_PROJECT_ID : {DATASTORE_PROJECT_ID}")
print(f"DATASTORE_LOCATION : {DATASTORE_LOCATION}")
print(f"DATASTORE_ENGINE_ID : {DATASTORE_ENGINE_ID}")
print(f"TOOLBOX_URL : {TOOLBOX_URL}")
print(f"MYSQL_HOST : {MYSQL_HOST}")
print(f"MYSQL_PORT : {MYSQL_PORT}")
print(f"MYSQL_USER : {MYSQL_USER}")
print(f"MYSQL_PASSWORD : {MYSQL_PASSWORD}")
print(f"GEMINI_MODEL : {GEMINI_MODEL}")
